python_tests(
    dependencies=[
        "tests/jira/fixtures",
        "tests/jira/fixtures:json_fixtures",
        "tests:init",
        ":init",
    ],
)

python_sources(
    name="init",
    sources=["__init__.py"],
)

python_sources(
    name="conftest",
    sources=["conftest.py"],
)
